### ISSUE TITLE
[Bug] Unable to compile project more than 7 directories away from C:

### ISSUE THREAD

**Issue by Zaph-x** [Zaph-x/Relanote#23]
**Describe the bug**

You are unable to compile the project, unless your project is located 7 directories away from `C:`

**Steps to reproduce**

Pull project 8 directories away from `C:`

**Expected behaviour**

Project should compile without problem

**Actual behaviour**

Project does not comile

**Comment by Rollerss** [comment]
Hello the only way I was able to get the app not to start up was if the folder path was too long. Do you think this could be the issue?

Program failed to start in this path:
C:\Users\Aname\OneDrive\Documents\GitHub\New folder\New folder\New folder\ThisIsAVeryLongFolderNameToSeeIfThePathLengthMakesTheErrorHappen\ThisIsAVeryLongFolderNameT\TTTTTTTTT0TTTTTTTTT0\Relanote

All of these folder paths worked:
C:\Relanote
C:\Users\Aname\OneDrive\Documents\GitHub\New folder\New folder\Relanote
C:\Users\Aname\OneDrive\Documents\GitHub\New folder\New folder\New folder\Relanote
C:\Users\Aname\OneDrive\Documents\GitHub\New folder\New folder\New folder\New folder\New folder\ThisIsAVeryLongFolderNameToSeeIfThePathLengthMakesTheErrorHappen\Relanote

**Comment by Zaph-x** [comment]
Hmm this is interesting. Is this after it's been compiled or our when it's being compiled and run?

The error I'm getting is that it cannot find the work library.

When looking in the csproj file, it seems that it expects a relative path to the dll, which is what my initial assumption was based on

**Comment by brandon-irl** [comment]
> 
> 
> When looking in the csproj file, it seems that it expects a relative path to the dll, which is what my initial assumption was based on

This most likely your problem. However, it is not clear why the Core proj requires this dependency in the first place, as this dependency is a UI library and therefore shouldn't be needed by anything "core". See my PR for one way to resolve this.
