### ISSUE TITLE
Image support

### ISSUE THREAD

**Issue by Zaph-x** [Zaph-x/Relanote#3]
Add a way to store images for notes.
This way you can take a screenshot of your lecture slides and store then in relation to your notes

**Comment by nelsonsvo** [comment]
I'll give it a go

**Comment by Zaph-x** [comment]
Great! I will assign you the issue!

**Comment by nelsonsvo** [comment]
Hey sorry, I haven't had time to get round to the issue yet.🙃

**Comment by Zaph-x** [comment]
@nrowley No worries man! I've been caught up as well

**Comment by nelsonsvo** [comment]
Sorry man, been really busy might be able to help later.

for now leaving it open for others to help 😔
